services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
    environment:
      DOMAIN: ${DOMAIN}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED:-true}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      PUSH_ENABLED: ${PUSH_ENABLED:-false}
      PUSH_INSTALLATION_ID: ${PUSH_INSTALLATION_ID:-}
      PUSH_INSTALLATION_KEY: ${PUSH_INSTALLATION_KEY:-}
      YUBICO_CLIENT_ID: ${YUBICO_CLIENT_ID:-}
      YUBICO_SECRET_KEY: ${YUBICO_SECRET_KEY:-}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-}
      SMTP_FROM: ${SMTP_FROM:-}
      SMTP_SECURITY: ${SMTP_SECURITY:-starttls}
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SHOW_PASSWORD_HINT: "false"
    volumes:
      - vaultwarden_data:/data
    ports:
      - 8000:80

volumes:
  vaultwarden_data:
