services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    ports:
      - 3000:3000
    volumes:
      - linkwarden_data:/data/data
  database:
    image: postgres:alpine
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

volumes:
  linkwarden_data:
  database_data:
