services:
  minio:
    image: quay.io/minio/minio:latest
    command: server -console-address ":9001"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-miniopassword}
      MINIO_VOLUMES: "/data"
      MINIO_PROMETHEUS_URL: ${MINIO_PROMETHEUS_URL:-}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL:-}
      MINIO_DOMAIN: ${MINIO_DOMAIN:-}
      MINIO_COMPRESSION_ENABLE: "on"
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  minio_data:
